import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';
mkdirSync('test-results/visual', { recursive: true });
const browser = await chromium.launch({ channel:'chrome', headless:true });
const page = await browser.newPage({ viewport:{width:1440,height:1050} });
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3001');
await page.screenshot({path:'test-results/visual/login.png',fullPage:true});
await page.getByRole('button',{name:'Sign in to workspace'}).click();
await page.getByRole('heading',{name:'Production overview'}).waitFor();
await page.screenshot({path:'test-results/visual/dashboard.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(300);
console.log('Mobile overflow:',await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1&&getComputedStyle(e).position!=='absolute').map(e=>({tag:e.tagName,class:e.className,right:Math.round(e.getBoundingClientRect().right)})).slice(0,25)})));
await page.screenshot({path:'test-results/visual/mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1050});
await page.getByRole('button',{name:/Review queue/}).click();
await page.getByRole('button',{name:/Open AX-MB/}).first().click();
await page.getByRole('heading',{name:'Human review'}).waitFor();
await page.screenshot({path:'test-results/visual/detail.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'test-results/visual/detail-mobile.png',fullPage:true});
console.log('Detail width:',await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth})));
console.log('Browser errors:',errors);
await browser.close();
