import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowDownToLine, ArrowLeft, ArrowRight, Box, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Cpu, Eye, EyeOff, Filter, Layers3, LayoutDashboard, Loader2, LockKeyhole, LogOut, Menu, Play, RefreshCw, RotateCw, Search, ShieldCheck, SlidersHorizontal, TriangleAlert, X, XCircle, ZoomIn, ZoomOut } from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import Board from './Board';
import './styles.css';

async function api(path, options = {}) {
  const response = await fetch(`/api${path}`, { credentials: 'same-origin', ...options, headers: { 'Content-Type': 'application/json', ...options.headers } });
  const data = await response.json();
  if (!response.ok) { const error = new Error(data.error || 'Request failed.'); error.status = response.status; throw error; }
  return data;
}
const time = value => new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
const date = value => new Date(value).toLocaleDateString([], { month: 'short', day: 'numeric' });
const count = value => new Intl.NumberFormat().format(value);
const statusLabel = { PASS: 'Passed', FAIL: 'Failed', REVIEW: 'Needs review', UNAVAILABLE: 'Unavailable', RUNNING: 'Running', ATTENTION: 'Attention', IDLE: 'Idle' };
function Badge({ status }) { return <span className={`badge ${status.toLowerCase()}`}><i/>{statusLabel[status] || status}</span>; }
function Logo() { return <div className="logo"><span className="logo-mark"><Layers3 size={23}/></span>axion<span className="logo-dot">.</span></div>; }
function Spinner() { return <div className="loading"><Loader2 className="spin"/> Loading workspaceâ€¦</div>; }

function Login({ onLogin }) {
  const [email, setEmail] = useState('inspector@axion.demo'); const [password, setPassword] = useState('Demo@123');
  const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { onLogin(await api('/login', { method: 'POST', body: JSON.stringify({ email, password }) })); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  return <div className="login"><section className="login-story"><Logo/><div className="login-copy"><span className="eyebrow">PRECISION AT EVERY STAGE</span><h1>Better quality.<br/>A clearer picture.</h1><p>From production line to final decision.<br/>Your inspection workflow, connected.</p></div><div className="login-board"><Board defects={[{id:1,x:424,y:270,width:80,height:65}]} selected={1}/><div className="floating-label"><ShieldCheck size={20}/><div><strong>Every decision, traceable.</strong><small>Evidence. Insight. Human expertise.</small></div></div></div><div className="login-footer"><span>AXION QUALITY WORKSPACE</span><span>Built for manufacturing.</span></div></section><section className="login-form"><div className="demo-tag"><span/> INTERACTIVE CUSTOMER DEMO</div><div className="login-form-inner"><div className="login-icon"><LockKeyhole size={24}/></div><h2>Welcome to your workspace</h2><p>Sign in to see quality in a different light.</p><form onSubmit={submit}><label>Email address<input autoComplete="username" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<div className="password-field"><input autoComplete="current-password" type={visible?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" className="icon-button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<div className="error" role="alert">{error}</div>}<button className="button primary login-submit" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<>Sign in to workspace <ArrowRight size={18}/></>}</button></form><div className="demo-credentials"><ShieldCheck size={20}/><div><strong>Your demo account is ready</strong><p>Use the prefilled credentials to explore as Maya Chen, Quality inspector.</p><code>inspector@axion.demo Â· Demo@123</code></div></div><p className="login-note">Simulated inspections. Real interactions.<br/>Changes are saved in this local demo.</p></div><div className="login-bottom">Quality you can see. Decisions you can trust.</div></section></div>;
}

function App() {
  const [user,setUser]=useState(null), [boot,setBoot]=useState(true), [workspace,setWorkspace]=useState(null), [page,setPage]=useState('overview');
  const [line,setLine]=useState('all'), [range,setRange]=useState('all'), [search,setSearch]=useState(''), [status,setStatus]=useState('all');
  const [toast,setToast]=useState(''), [error,setError]=useState(''), [busy,setBusy]=useState(false), [mobile,setMobile]=useState(false), [help,setHelp]=useState(false);
  const [detailId,setDetailId]=useState(location.hash.startsWith('#inspection/')?location.hash.split('/')[1]:null);
  useEffect(()=>{api('/me').then(setUser).catch(e=>{if(e.status!==401)setError('Could not connect to the demo server. Start the application and reload.');}).finally(()=>setBoot(false));},[]);
  useEffect(()=>{ const handler=()=>setDetailId(location.hash.startsWith('#inspection/')?location.hash.split('/')[1]:null); window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler);},[]);
  async function reload() { try { setError(''); const data=await api('/workspace');setWorkspace(data); } catch(e){setError(e.message);if(e.status===401)setUser(null);} }
  useEffect(()=>{if(user)reload();},[user]);
  useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);}},[toast]);
  function navigate(next){setPage(next);setMobile(false);setSearch('');setStatus('all');location.hash='';}
  function openBoard(id){location.hash=`inspection/${id}`;setMobile(false);window.scrollTo(0,0);}
  async function logout(){try{await api('/logout',{method:'POST'});setUser(null);setWorkspace(null);location.hash='';}catch(e){setError(e.message);}}
  async function simulate(){setBusy(true);try{await api('/simulate',{method:'POST'});await reload();setToast('New simulated inspection added to the review queue.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  const scoped=useMemo(()=>workspace?.inspections.filter(i=>(line==='all'||i.line_id===line)&&(range==='all'||Date.now()-new Date(i.captured_at).getTime()<Number(range)*3600000))||[],[workspace,line,range]);
  const filtered=useMemo(()=>scoped.filter(i=>(page!=='reviews'||i.status==='REVIEW')&&(status==='all'||i.status===status)&&`${i.board_id} ${i.id} ${i.product} ${i.line_name}`.toLowerCase().includes(search.toLowerCase())),[scoped,page,status,search]);
  if(boot)return <Spinner/>;
  if(!user)return <>{error&&<div className="error connection-error" role="alert">{error}</div>}<Login onLogin={setUser}/></>;
  const reviewCount=workspace?.inspections.filter(i=>i.status==='REVIEW').length||0;
  function exportCsv(){const rows=[['Inspection','Board','Line','Product','Time','Initial disposition','Current disposition','Defects'],...filtered.map(i=>[i.id,i.board_id,i.line_name,i.product,i.captured_at,i.initial_status,i.status,i.defect_count])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='axion-demo-inspections.csv';a.click();URL.revokeObjectURL(url);setToast('Filtered inspection data exported.');}
  return <div className="app-shell">{mobile&&<button className="nav-backdrop" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}<aside className={`sidebar ${mobile?'open':''}`}><Logo/><div className="workspace-label"><span className="plant-icon"><Box size={18}/></span><div><strong>Colombo manufacturing</strong><small>Quality operations</small></div></div><span className="nav-caption">WORKSPACE</span><nav>{[[LayoutDashboard,'overview','Overview'],[Layers3,'lines','Production lines'],[TriangleAlert,'reviews','Review queue'],[Cpu,'inspections','Inspections']].map(([Icon,key,label])=><button key={key} className={page===key&&!detailId?'active':''} onClick={()=>navigate(key)}><Icon size={19}/><span>{label}</span>{key==='reviews'&&<b>{reviewCount}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-panel"><span className="demo-indicator"/><strong>Demo environment</strong><p>Sample data. No production equipment connected.</p></div><button className="help-button" onClick={()=>setHelp(true)}><CircleHelp size={18}/> Demo walkthrough <ArrowRight size={16}/></button><div className="user-profile"><span className="avatar">MC</span><div><strong>{user.name}</strong><small>{user.role}</small></div><button className="icon-button" onClick={logout} aria-label="Sign out"><LogOut size={17}/></button></div></div></aside>
    <main className="main"><header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div className="breadcrumb">Workspace <span>/</span> <strong>{detailId?'Inspection detail':{overview:'Overview',lines:'Production lines',reviews:'Review queue',inspections:'Inspections'}[page]}</strong></div><div className="topbar-right"><span className="demo-pill">DEMO</span><span className="today">{new Date().toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}</span><span className="avatar small">MC</span></div></header>
    {error&&<div className="error global-error" role="alert">{error}<button onClick={reload}>Retry</button></div>}
    {!workspace?<Spinner/>:detailId?<Detail id={detailId} onBack={()=>{location.hash='';}} onSaved={async()=>{await reload();setToast('Review decision saved. Inspection history updated.');}} user={user}/>:<div className="page-content"><div className="page-heading"><div><div className="eyebrow">QUALITY OPERATIONS</div><h1>{{overview:'Production overview',lines:'Your production lines',reviews:'A second look matters.',inspections:'Inspection history'}[page]}</h1><p>{{overview:'A clear view of your lines. Confidence in every decision.',lines:'Monitor inspection quality across your manufacturing floor.',reviews:'Review flagged boards and bring human expertise to the final decision.',inspections:'Every board, every finding, every decision â€” in one place.'}[page]}</p></div><div className="heading-actions"><button className="button" onClick={exportCsv}><ArrowDownToLine size={16}/> Export</button><button className="button primary" disabled={busy} onClick={simulate}>{busy?<Loader2 size={16} className="spin"/>:<Play size={16}/>} Simulate inspection</button></div></div>
      <div className="filterbar"><div className="filter-group"><label><Filter size={16}/><select aria-label="Production line" value={line} onChange={e=>setLine(e.target.value)}><option value="all">All production lines</option>{workspace.lines.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label><Clock3 size={16}/><select aria-label="Time period" value={range} onChange={e=>setRange(e.target.value)}><option value="all">All demo data</option><option value="8">Last 8 hours</option><option value="1">Last hour</option></select></label></div><button className="refresh" onClick={reload}><RefreshCw size={14}/> Updated {time(workspace.generatedAt)}</button></div>
      {(page==='overview'||page==='lines')&&<><Metrics inspections={scoped}/><section className="line-section"><div className="section-heading"><h2>Production lines <span className="count">04</span></h2><span className="muted">Simulated equipment status</span></div><div className="line-grid">{workspace.lines.map(l=>{const rows=workspace.inspections.filter(i=>i.line_id===l.id&&(range==='all'||Date.now()-new Date(i.captured_at).getTime()<Number(range)*3600000));const yieldValue=rows.length?((rows.filter(i=>i.status==='PASS').length/rows.length)*100).toFixed(1):'0.0';return <button className={`line-card ${line===l.id?'selected':''}`} key={l.id} onClick={()=>setLine(line===l.id?'all':l.id)}><div className="line-card-top"><span className="line-icon"><Layers3 size={19}/></span><Badge status={l.status}/></div><h3>{l.name}</h3><p>{l.product} <span>â€¢</span> {l.camera}</p><div className="line-numbers"><div><strong>{rows.length}</strong><small>Inspected</small></div><div><strong>{yieldValue}<em>%</em></strong><small>Pass rate</small></div><div><strong className={rows.some(i=>i.status==='REVIEW')?'orange':''}>{rows.filter(i=>i.status==='REVIEW').length}</strong><small>To review</small></div></div><div className="progress-track"><span style={{width:`${yieldValue}%`}}/></div><div className="line-foot">{line===l.id?'Showing this line':'View line inspections'}<ArrowRight size={14}/></div></button>;})}</div></section></>}
      {page==='overview'&&<Analytics inspections={scoped} defects={workspace.defects}/>}
      {page==='reviews'&&<div className="review-banner"><span className="review-banner-icon"><TriangleAlert size={24}/></span><div><h3>{filtered.length} boards need your expertise</h3><p>Inspect the evidence, document your reasoning, and confirm a disposition. Physical actions are simulated.</p></div><ShieldCheck size={32}/></div>}
      <InspectionTable inspections={filtered} onOpen={openBoard} search={search} setSearch={setSearch} status={status} setStatus={setStatus} reviewMode={page==='reviews'} title={page==='overview'?'Recent inspections':page==='reviews'?'Awaiting human review':'Inspection records'}/>
      <footer className="page-footer"><span><ShieldCheck size={14}/> Traceable by design. Human expertise at the center.</span><span>Sample metrics Â· Illustrated evidence Â· Local demo</span></footer></div>}
    </main>{toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}<button className="icon-button" onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={16}/></button></div>}
    {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="walkthrough-title" onClick={e=>e.stopPropagation()}><button autoFocus className="icon-button modal-close" aria-label="Close walkthrough" onClick={()=>setHelp(false)}><X/></button><span className="eyebrow">A QUICK TOUR</span><h2 id="walkthrough-title">Follow a board's journey.</h2><ol className="walkthrough"><li><strong>Explore the floor</strong><p>Filter by line or time period and inspect the dashboard.</p></li><li><strong>Open the review queue</strong><p>Select a board, zoom into its illustrated evidence, and choose a defect.</p></li><li><strong>Make the human decision</strong><p>Choose pass, fail, or escalation. Add a reason and confirm.</p></li><li><strong>See the impact</strong><p>Return to the dashboard. Counts and decision history update and persist.</p></li></ol><button className="button primary" onClick={()=>{setHelp(false);navigate('reviews');}}>Open review queue <ArrowRight size={17}/></button></section></div>}
  </div>;
}

function Metrics({inspections}){const total=inspections.length, pass=inspections.filter(i=>i.status==='PASS').length, fail=inspections.filter(i=>i.status==='FAIL').length, review=inspections.filter(i=>i.status==='REVIEW').length, unavailable=inspections.filter(i=>i.status==='UNAVAILABLE').length;return <div className="metrics">{[[Cpu,'Boards inspected',count(total),`${unavailable} unavailable Â· current selection`,'neutral'],[CheckCircle2,'Pass rate',`${total?(pass/total*100).toFixed(1):'0.0'}%`,`${count(pass)} boards passed`,'green'],[XCircle,'Failed boards',count(fail),'Current authoritative disposition','red'],[TriangleAlert,'Awaiting review',count(review),'Human intervention required','orange']].map(([Icon,label,value,sub,color])=><div className={`metric ${color}`} key={label}><div className="metric-label">{label}<Icon size={19}/></div><strong>{value}</strong><small>{sub}</small></div>)}</div>;}

function Analytics({inspections,defects}){
  const bins=useMemo(()=>{if(!inspections.length)return [];const end=Math.max(...inspections.map(i=>new Date(i.captured_at).getTime()));const start=new Date(end).setMinutes(0,0,0)-7*3600000;return Array.from({length:8},(_,index)=>{const at=start+index*3600000;const rows=inspections.filter(i=>{const t=new Date(i.captured_at).getTime();return t>=at&&t<at+3600000;});return {label:time(at),Passed:rows.filter(i=>i.status==='PASS').length,Flagged:rows.filter(i=>['FAIL','REVIEW'].includes(i.status)).length};});},[inspections]);
  const ids=new Set(inspections.map(i=>i.id));const visible=defects.filter(d=>ids.has(d.inspection_id));const types=['Solder bridge','Missing component','Misalignment'];
  return <div className="analytics-grid"><section className="panel chart-panel"><div className="section-heading"><div><h2>Inspection activity</h2><p>Hourly outcomes Â· latest eight-hour window</p></div><div className="legend"><span><i className="green-dot"/>Passed</span><span><i className="orange-dot"/>Flagged</span></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={bins} margin={{top:12,right:10,left:-25,bottom:0}}><defs><linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#4a8b77" stopOpacity={.2}/><stop offset="1" stopColor="#4a8b77" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e8edeb"/><XAxis dataKey="label" tick={{fontSize:11,fill:'#7c8889'}} axisLine={false} tickLine={false} minTickGap={20}/><YAxis allowDecimals={false} tick={{fontSize:11,fill:'#7c8889'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:10,border:'1px solid #e2e8e4',fontSize:12}}/><Area isAnimationActive={false} type="monotone" dataKey="Passed" stroke="#43846e" strokeWidth={2.5} fill="url(#chartGradient)"/><Area isAnimationActive={false} type="monotone" dataKey="Flagged" stroke="#ea8752" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div></section><section className="panel defect-summary"><div className="section-heading"><div><h2>Defect breakdown</h2><p>Original findings Â· {visible.length} detections</p></div><SlidersHorizontal size={18}/></div>{types.map((type,index)=>{const n=visible.filter(d=>d.type===type).length;const percent=visible.length?Math.round(n/visible.length*100):0;return <div className="defect-distribution" key={type}><div><span><i style={{background:['#ed8053','#e8b16b','#81a89a'][index]}}/>{type}</span><strong>{n} <small>({percent}%)</small></strong></div><div className="progress-track"><span style={{width:`${percent}%`,background:['#ed8053','#e8b16b','#81a89a'][index]}}/></div></div>})}<div className="insight"><Activity size={17}/><span>Findings remain in history after a human override.</span></div></section></div>;
}

function InspectionTable({inspections,onOpen,search,setSearch,status,setStatus,reviewMode,title}){
  const [page,setPage]=useState(0);const size=8;useEffect(()=>setPage(0),[search,status,inspections.length]);const last=Math.max(0,Math.ceil(inspections.length/size)-1);const current=Math.min(page,last);const visible=inspections.slice(current*size,current*size+size);
  return <section className="panel table-panel"><div className="section-heading table-heading"><h2>{title} <span className="count">{inspections.length}</span></h2><div className="table-controls"><div className="search-field"><Search size={16}/><input aria-label="Search inspections" placeholder="Search board or inspectionâ€¦" value={search} onChange={e=>setSearch(e.target.value)}/></div>{!reviewMode&&<select aria-label="Inspection status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['PASS','FAIL','REVIEW','UNAVAILABLE'].map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select>}</div></div><div className="table-scroll"><table><thead><tr><th>BOARD / INSPECTION</th><th>PRODUCTION LINE</th><th>CAPTURED</th><th>STATUS</th><th>DEFECTS</th><th>MODEL SCORE</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{visible.map(i=><tr key={i.id} onClick={()=>onOpen(i.id)}><td><div className="board-cell"><span className="board-icon"><Cpu size={18}/></span><div><strong>{i.board_id}</strong><small>{i.id} Â· {i.product}</small></div></div></td><td>{i.line_name}<small>{i.batch}</small></td><td>{time(i.captured_at)}<small>{date(i.captured_at)}</small></td><td><Badge status={i.status}/></td><td>{i.defect_count?<span className="defect-number">{i.defect_count} detected</span>:<span className="muted">â€”</span>}</td><td>{i.confidence===null?'â€”':`${i.confidence.toFixed(1)}%`}</td><td><button className="row-action" aria-label={`Open ${i.board_id}`} onClick={e=>{e.stopPropagation();onOpen(i.id);}}>{i.status==='REVIEW'?'Review':'View'}<ArrowRight size={15}/></button></td></tr>)}</tbody></table>{!visible.length&&<div className="empty-state"><Search size={30}/><h3>No matching inspections</h3><p>Try another line, time period, or search term.</p></div>}</div><div className="table-footer"><span>{inspections.length?`${current*size+1}â€“${Math.min((current+1)*size,inspections.length)} of ${inspections.length} inspections`:'0 inspections'}</span><div><button className="icon-button" aria-label="Previous page" disabled={!current} onClick={()=>setPage(current-1)}><ChevronLeft size={18}/></button><span>Page {current+1} of {last+1}</span><button className="icon-button" aria-label="Next page" disabled={current===last} onClick={()=>setPage(current+1)}><ChevronRight size={18}/></button></div></div></section>;
}

function Detail({id,onBack,onSaved,user}){
  const [board,setBoard]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(null),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0),[overlays,setOverlays]=useState(true),[decision,setDecision]=useState('FAIL'),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[tab,setTab]=useState('findings');
  async function load(){try{setError('');const b=await api(`/inspections/${id}`);setBoard(b);setSelected(b.defects[0]?.id);}catch(e){setError(e.message);}}
  useEffect(()=>{setBoard(null);setReason('');setZoom(1);setRotation(0);setTab('findings');load();},[id]);
  async function save(){setBusy(true);try{await api(`/inspections/${id}/review`,{method:'POST',body:JSON.stringify({decision,reason,version:board.version})});setConfirm(false);setReason('');await load();await onSaved();}catch(e){setConfirm(false);setError(e.message);}finally{setBusy(false);}}
  if(!board)return <div className="page-content"><button className="back-link" onClick={onBack}><ArrowLeft size={16}/> Back to workspace</button>{error?<div className="error" role="alert">{error}<button onClick={load}>Retry</button></div>:<Spinner/>}</div>;
  return <div className="page-content detail-page"><button className="back-link" onClick={onBack}><ArrowLeft size={16}/> Back to workspace</button><div className="page-heading"><div><div className="eyebrow">INSPECTION / {board.id}</div><h1>{board.board_id} <Badge status={board.status}/></h1><p>{board.product} <span className="separator">/</span> {board.line_name} <span className="separator">/</span> {date(board.captured_at)}, {time(board.captured_at)}</p></div><span className="evidence-tag"><ShieldCheck size={16}/> Original evidence preserved</span></div>
    {error&&<div className="error" role="alert">{error}<button onClick={load}>Reload inspection</button></div>}
    <div className="detail-layout"><div className="detail-main"><section className="panel evidence-panel"><div className="section-heading"><div><h2>Board inspection view</h2><p>Top view Â· {board.camera} Â· Illustrated sample evidence</p></div><span className="demo-pill">SIMULATED</span></div><div className="board-stage"><div className="stage-label"><span/> TOP CAMERA / ORIGINAL COORDINATES</div><div className="board-viewport"><Board defects={board.defects} selected={selected} onSelect={setSelected} overlays={overlays} zoom={zoom} rotation={rotation}/></div><div className="stage-bottom"><span>ATX CORE Â· REFERENCE ILLUSTRATION</span><span>{Math.round(zoom*100)}%</span></div></div><div className="evidence-toolbar"><button className={`button compact ${overlays?'toggled':''}`} onClick={()=>setOverlays(!overlays)}>{overlays?<Eye size={16}/>:<EyeOff size={16}/>} Defect overlays</button><div><button className="icon-button" aria-label="Zoom out" disabled={zoom<=.75} onClick={()=>setZoom(Math.max(.75,zoom-.25))}><ZoomOut size={18}/></button><button className="icon-button" aria-label="Zoom in" disabled={zoom>=2} onClick={()=>setZoom(Math.min(2,zoom+.25))}><ZoomIn size={18}/></button><button className="icon-button" aria-label="Rotate board" onClick={()=>setRotation((rotation+90)%360)}><RotateCw size={18}/></button><button className="reset-view" onClick={()=>{setZoom(1);setRotation(0);}}>Reset view</button></div></div></section>
    <section className="panel findings-panel"><div className="tabs"><button className={tab==='findings'?'active':''} onClick={()=>setTab('findings')}>Detected defects <span>{board.defects.length}</span></button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>Decision history <span>{board.audit.length}</span></button></div>{tab==='findings'?<div className="findings">{board.defects.map((d,i)=><button key={d.id} className={`finding ${selected===d.id?'selected':''}`} onClick={()=>{setSelected(d.id);setOverlays(true);}}><span className="finding-index">{i+1}</span><div><strong>{d.type} <span className={`severity ${d.severity.toLowerCase()}`}>{d.severity}</span></strong><small>{d.component}</small></div><div className="finding-score"><strong>{d.confidence.toFixed(1)}%</strong><small>Model score</small></div><ChevronRight size={17}/></button>)}{!board.defects.length&&<div className="empty-state"><ShieldCheck size={28}/><h3>{board.status==='UNAVAILABLE'?'Evidence incomplete':'No defects detected'}</h3><p>{board.status==='UNAVAILABLE'?'A required camera view was unavailable. Re-imaging is needed.':'This sample inspection has no model findings.'}</p></div>}<p className="score-note">Model scores are simulated confidence values, not validated defect probabilities.</p></div>:<div className="timeline">{board.audit.map(a=><div className="timeline-item" key={a.id}><span className="timeline-dot"/><div><strong>{a.action}</strong><p>{a.detail}</p><small>{a.actor} Â· {date(a.created_at)} at {time(a.created_at)}</small></div></div>)}</div>}</section></div>
    <aside className="detail-aside"><section className="panel review-card"><div className="review-card-heading"><span><ShieldCheck size={21}/></span><div><h2>Human review</h2><p>Your expertise. The final decision.</p></div></div><div className="review-context"><span>Original AI disposition</span><Badge status={board.initial_status}/></div><div className="review-context"><span>Reviewing as</span><strong>{user.name}</strong></div>{board.initial_status==='UNAVAILABLE'?<div className="callout"><TriangleAlert size={20}/><p>Incomplete inspections cannot be released. This board requires re-imaging through the approved operational workflow.</p></div>:<form onSubmit={e=>{e.preventDefault();setConfirm(true);}}><label className="field-label">Select a disposition</label><div className="decision-options">{[['FAIL',XCircle,'Confirm failure','Keep the board rejected'],['PASS',CheckCircle2,'Override to pass','Accept after manual verification'],['REVIEW',TriangleAlert,'Escalate review','Keep pending for a second opinion']].map(([key,Icon,title,desc])=><label key={key} className={`decision-option ${decision===key?'selected':''}`}><input type="radio" name="decision" value={key} checked={decision===key} onChange={()=>setDecision(key)}/><Icon size={19}/><span><strong>{title}</strong><small>{desc}</small></span><span className="radio-dot"/></label>)}</div><label className="field-label" htmlFor="reason">Decision reason <span>Required</span></label><textarea id="reason" value={reason} minLength={10} maxLength={2000} required onChange={e=>setReason(e.target.value)} placeholder="Describe what you observed and why this disposition is appropriateâ€¦" rows="4"/><div className="reason-meta"><span>Minimum 10 characters</span><span>{reason.length}/2000</span></div>{decision==='PASS'&&board.defects.some(d=>d.severity==='Critical')&&<div className="callout"><TriangleAlert size={19}/><p>A critical finding is present. An override requires explicit manual verification and a documented reason.</p></div>}<button className="button primary submit-review" disabled={reason.trim().length<10}>Save review decision <ArrowRight size={17}/></button><p className="review-disclaimer"><LockKeyhole size={13}/> Saved with your identity and timestamp.<br/>No physical line action will be performed.</p></form>}</section>
    <section className="panel trace-card"><h2>Inspection traceability</h2>{[['Inspection ID',board.id],['Batch',board.batch],['Model version',board.model],['Rule recipe',board.recipe],['Inference latency',`${board.latency} ms Â· sample`],['Record version',`v${board.version}`],['Evidence','Illustrated demo Â· top view']].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</section></aside></div>
    {confirm&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><span className="eyebrow">CONFIRM HUMAN DECISION</span><h2 id="confirm-title">{decision==='PASS'?'Release as passed?':decision==='FAIL'?'Confirm this board failed?':'Escalate this inspection?'}</h2><p>Your decision for <strong>{board.board_id}</strong> will be recorded. The original AI disposition remains in history.</p><blockquote>{reason}</blockquote><div className="modal-actions"><button autoFocus className="button" disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button><button className="button primary" disabled={busy} onClick={save}>{busy?<Loader2 className="spin" size={17}/>:<Check size={17}/>} Confirm decision</button></div></section></div>}
  </div>;
}

createRoot(document.getElementById('root')).render(<App/>);
